### ISSUE TITLE
Many workers exiting while the scan is still largely incomplete

### ISSUE THREAD

**Issue by mlincett** [WIPACrepo/SkyDriver#84] opened 2023-10-17 12:09 UTC
I am still running into scenarios with jobs moving to `DONE` state while many pixels are still pending.

Scan `e5cafa4bbd824657a6e009d7d63d7132` at around 1/4 progress had already more than half of the jobs in `DONE` state. NSIDE progression is `{'8': 0, '64': 12, '512': 24} ` and total pixels are around ~ 25k. NSIDE 8 involves already ~5k pixels with SplineMPE so I don't see how clients could get starved. Timeout is in the order of minutes, which should be plenty for any single SplineMPE reco.

It could be nice to better understand what can cause a worker to transition into `DONE` state prematurely.

**Comment by ric-evans** [comment] 2023-10-17 21:51
interesting -- I see the scan finished, so that's good. Do you have a rough timeline of when the jobs started exiting?

**Comment by ric-evans** [comment] 2023-11-17 23:39
This has potentially been fixed by https://github.com/Observation-Management-Service/ewms-pilot/releases/tag/v0.17.2, we'll need to run at scale to confirm

**Comment by G-Sommani** [comment] 2023-11-20 13:30
I am noticing the same issue with the scan 8b7741e7420d4f6b925c4c58d53b14bd, even in a worse version. 97 jobs immediately went on DONE while 3 jobs remained to do basiclly all the scan (on 100 jobs)

**Comment by ric-evans** [comment] 2023-12-15 22:21
Closing for now, as it seems the root cause(s) have been fixed. Feel free to re-open if you see this again.

**Closed by ric-evans** 2023-12-15 22:21 UTC
Labels: question
